packages:
  - 'backend'
  - 'frontend'
allowBuilds:
  '@nestjs/core': true
  '@stellar/stellar-sdk': true
  '@swc/core': true
  blake-hash: true
  bufferutil: true
  esbuild: true
  protobufjs: true
  tiny-secp256k1: true
  usb: true
  utf-8-validate: true
