packages:
  - 'backend'
  - 'frontend'
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@stellar/stellar-sdk'
  - '@swc/core'
  - blake-hash
  - bufferutil
  - esbuild
  - protobufjs
  - tiny-secp256k1
  - usb
  - utf-8-validate
